name: riverpod_keepalive_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0

dependencies:
  flutter:
    sdk: flutter
  
  riverpod: ^2.0.0
  riverpod_annotation: ^2.0.0
  flutter_riverpod: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.0.0
  riverpod_generator: ^2.0.0
  custom_lint:
  riverpod_lint:

flutter:
  uses-material-design: true
